import {
  Hct,
  SchemeContent,
  SchemeExpressive,
  SchemeFidelity,
  SchemeFruitSalad,
  SchemeMonochrome,
  SchemeNeutral,
  SchemeRainbow,
  SchemeTonalSpot,
  SchemeVibrant,
  argbFromHex,
  customColor,
  hexFromArgb,
} from '@poupe/material-color-utilities'
import type { DynamicScheme } from '@poupe/material-color-utilities'

import type {
  MaterialColorPlatform,
  MaterialColorSpecVersion,
  MaterialColorVariant,
  MaterialColorsConfig,
  MaterialCustomColorConfig,
  MaterialCustomColorsConfig,
} from '../types'

type SchemeMode = 'dark' | 'light'

type MaterialColorRole = (typeof materialColorRoles)[number]

type SchemeConstructor = new (
  sourceColorHct: Hct,
  isDark: boolean,
  contrastLevel: number,
  specVersion?: MaterialColorSpecVersion,
  platform?: MaterialColorPlatform,
) => DynamicScheme

type CustomColorSlot = Extract<keyof MaterialCustomColorsConfig, string>
type ResolvedMaterialCustomColorsConfig = Record<
  CustomColorSlot,
  MaterialCustomColorConfig
>

const transparentSurfaceAlpha = 'f3'

const transparentSurfaceRoles = new Set<MaterialColorRole>([
  'surfaceContainerLowest',
  'surfaceContainerLow',
  'surfaceContainer',
  'surfaceContainerHigh',
  'surfaceContainerHighest',
])

type ResolvedMaterialColorsConfig = Omit<MaterialColorsConfig, 'custom'> & {
  custom: ResolvedMaterialCustomColorsConfig
}

const customColorSlotPattern = /^[a-z][a-z0-9-]*$/

const materialColorRoles = [
  'primary',
  'onPrimary',
  'primaryContainer',
  'onPrimaryContainer',
  'inversePrimary',
  'primaryFixed',
  'primaryFixedDim',
  'onPrimaryFixed',
  'onPrimaryFixedVariant',
  'secondary',
  'onSecondary',
  'secondaryContainer',
  'onSecondaryContainer',
  'secondaryFixed',
  'secondaryFixedDim',
  'onSecondaryFixed',
  'onSecondaryFixedVariant',
  'tertiary',
  'onTertiary',
  'tertiaryContainer',
  'onTertiaryContainer',
  'tertiaryFixed',
  'tertiaryFixedDim',
  'onTertiaryFixed',
  'onTertiaryFixedVariant',
  'error',
  'onError',
  'errorContainer',
  'onErrorContainer',
  'background',
  'onBackground',
  'surface',
  'surfaceDim',
  'surfaceBright',
  'surfaceContainerLowest',
  'surfaceContainerLow',
  'surfaceContainer',
  'surfaceContainerHigh',
  'surfaceContainerHighest',
  'onSurface',
  'surfaceVariant',
  'onSurfaceVariant',
  'outline',
  'outlineVariant',
  'inverseSurface',
  'inverseOnSurface',
  'shadow',
  'scrim',
  'surfaceTint',
] as const

const schemeConstructors = {
  content: SchemeContent,
  expressive: SchemeExpressive,
  fidelity: SchemeFidelity,
  fruitSalad: SchemeFruitSalad,
  monochrome: SchemeMonochrome,
  neutral: SchemeNeutral,
  rainbow: SchemeRainbow,
  tonalSpot: SchemeTonalSpot,
  vibrant: SchemeVibrant,
} satisfies Record<MaterialColorVariant, SchemeConstructor>

export const defaultMaterialColorsConfig = {
  source: '#76B7E7',
  variant: 'tonalSpot',
  contrastLevel: 0,
  specVersion: '2025',
  platform: 'phone',
  custom: {
    blue: { color: '#D5ECF6', blend: true },
    brown: { color: '#A0703C', blend: true },
    pink: { color: '#C87D6F', blend: true },
    valaxy: { color: '#9810fa', blend: true },
  },
} satisfies MaterialColorsConfig

export function generateMaterialColorsCss(input?: Partial<MaterialColorsConfig>) {
  const config = resolveMaterialColorsConfig(input)
  const sourceArgb = parseHexColor(config.source, 'source')
  const lightScheme = createScheme(config, sourceArgb, false)
  const darkScheme = createScheme(config, sourceArgb, true)
  const customColorLines = createCustomColorLines(config.custom, sourceArgb)

  return [
    '/* Generated by valaxy-theme-lgcuwukii from themeConfig.colors. */',
    ':root {',
    ...createSchemeLines(lightScheme),
    ...customColorLines.light,
    '}',
    '',
    'html.dark {',
    ...createSchemeLines(darkScheme),
    ...customColorLines.dark,
    '}',
    '',
  ].join('\n')
}

function resolveMaterialColorsConfig(
  input: Partial<MaterialColorsConfig> = {},
): ResolvedMaterialColorsConfig {
  const config = {
    ...defaultMaterialColorsConfig,
    ...input,
    custom: resolveCustomColorsConfig(
      input.source ?? defaultMaterialColorsConfig.source,
      input.custom,
    ),
  } satisfies ResolvedMaterialColorsConfig

  validateMaterialColorsConfig(config)

  return config
}

function resolveCustomColorsConfig(
  source: string,
  input: MaterialCustomColorsConfig | undefined,
): ResolvedMaterialCustomColorsConfig {
  const defaults = resolveDefaultCustomColorsConfig(source)

  return Object.fromEntries(
    objectEntries(defaults).map(([slot, defaultConfig]) => [
      slot,
      resolveCustomColorConfig(defaultConfig, input?.[slot]),
    ]),
  ) as ResolvedMaterialCustomColorsConfig
}

function resolveDefaultCustomColorsConfig(
  source: string,
): Record<CustomColorSlot, MaterialCustomColorConfig> {
  return {
    ...defaultMaterialColorsConfig.custom,
    blue: {
      ...defaultMaterialColorsConfig.custom.blue,
      color: source,
    },
  }
}

function resolveCustomColorConfig(
  defaults: MaterialCustomColorConfig,
  input: Partial<MaterialCustomColorConfig> | undefined,
): MaterialCustomColorConfig {
  return {
    color: input?.color ?? defaults.color,
    blend: input?.blend ?? defaults.blend ?? true,
  }
}

function validateMaterialColorsConfig(config: ResolvedMaterialColorsConfig) {
  parseHexColor(config.source, 'source')

  if (!Number.isFinite(config.contrastLevel)) {
    throw new TypeError(
      '[valaxy-theme-lgcuwukii] themeConfig.colors.contrastLevel must be a finite number.',
    )
  }

  if (config.contrastLevel < -1 || config.contrastLevel > 1) {
    throw new Error(
      '[valaxy-theme-lgcuwukii] themeConfig.colors.contrastLevel must be between -1 and 1.',
    )
  }

  if (!(config.variant in schemeConstructors)) {
    throw new Error(
      `[valaxy-theme-lgcuwukii] themeConfig.colors.variant "${config.variant}" is not supported.`,
    )
  }

  if (config.specVersion !== '2021' && config.specVersion !== '2025') {
    throw new Error(
      `[valaxy-theme-lgcuwukii] themeConfig.colors.specVersion "${config.specVersion}" is not supported.`,
    )
  }

  if (config.platform !== 'phone' && config.platform !== 'watch') {
    throw new Error(
      `[valaxy-theme-lgcuwukii] themeConfig.colors.platform "${config.platform}" is not supported.`,
    )
  }

  objectEntries(config.custom).forEach(([slot, colorConfig]) => {
    validateCustomColorSlot(slot)
    parseHexColor(colorConfig.color, `custom.${slot}.color`)
  })
}

function createScheme(
  config: ResolvedMaterialColorsConfig,
  sourceArgb: number,
  isDark: boolean,
) {
  const Scheme = schemeConstructors[config.variant]

  return new Scheme(
    Hct.fromInt(sourceArgb),
    isDark,
    config.contrastLevel,
    config.specVersion,
    config.platform,
  )
}

function createSchemeLines(scheme: DynamicScheme) {
  return materialColorRoles.flatMap((role) => {
    const argb = getSchemeRoleArgb(scheme, role)
    if (argb === undefined) return []

    return `  --md-sys-color-${kebabCase(role)}: ${formatRoleColor(role, argb)};`
  })
}

function getSchemeRoleArgb(scheme: DynamicScheme, role: MaterialColorRole) {
  try {
    const value = (scheme as unknown as Record<MaterialColorRole, number>)[role]

    return Number.isFinite(value) ? value : undefined
  } catch {
    return undefined
  }
}

function createCustomColorLines(
  custom: ResolvedMaterialCustomColorsConfig,
  sourceArgb: number,
): Record<SchemeMode, string[]> {
  return {
    light: createCustomColorModeLines(custom, sourceArgb, 'light'),
    dark: createCustomColorModeLines(custom, sourceArgb, 'dark'),
  }
}

function createCustomColorModeLines(
  custom: ResolvedMaterialCustomColorsConfig,
  sourceArgb: number,
  mode: SchemeMode,
) {
  return objectEntries(custom).flatMap(([slot, config]) => {
    const group = customColor(sourceArgb, {
      name: slot,
      value: parseHexColor(config.color, `custom.${slot}.color`),
      blend: config.blend ?? true,
    })

    return createCustomColorGroupLines(slot, group[mode])
  })
}

function createCustomColorGroupLines(
  slot: CustomColorSlot,
  group: ReturnType<typeof customColor>[SchemeMode],
) {
  return [
    `  --md-custom-color-${slot}: ${hexFromArgb(group.color)};`,
    `  --md-custom-color-on-${slot}: ${hexFromArgb(group.onColor)};`,
    `  --md-custom-color-${slot}-container: ${hexFromArgb(group.colorContainer)};`,
    `  --md-custom-color-on-${slot}-container: ${hexFromArgb(group.onColorContainer)};`,
  ]
}

function formatRoleColor(role: MaterialColorRole, argb: number) {
  const color = hexFromArgb(argb)

  if (!transparentSurfaceRoles.has(role)) return color

  return `${color}${transparentSurfaceAlpha}`
}

function parseHexColor(color: unknown, field: string) {
  if (typeof color !== 'string') {
    throw new TypeError(
      `[valaxy-theme-lgcuwukii] themeConfig.colors.${field} must be a hex color string.`,
    )
  }

  try {
    return argbFromHex(color)
  } catch {
    throw new Error(
      `[valaxy-theme-lgcuwukii] themeConfig.colors.${field} must be a valid hex color, received "${color}".`,
    )
  }
}

function validateCustomColorSlot(slot: string) {
  if (customColorSlotPattern.test(slot)) return

  throw new Error(
    `[valaxy-theme-lgcuwukii] themeConfig.colors.custom slot "${slot}" must use lowercase kebab-case.`,
  )
}

function kebabCase(value: string) {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}

function objectEntries<T extends object>(value: T) {
  type EntryKey = Extract<keyof T, string>

  return Object.entries(value) as [EntryKey, T[EntryKey]][]
}
