semi: false
singleQuote: true
printWidth: 88

plugins:
  - '@trivago/prettier-plugin-sort-imports'

importOrder:
  - '^node:(.*)$' # builtin
  - '^(@[^\/]|[^\.@])(.*)$' # external
  - '.*' # local
importOrderSeparation: true
importOrderSortSpecifiers: true
