catalogMode: prefer
cleanupUnusedCatalogs: true

packages:
  - blog
  - demo
  - theme

allowBuilds:
  '@parcel/watcher': true
  cn-font-split: true
  core-js: false
  esbuild: true
  koffi: true
  protobufjs: true
  sharp: false
  vue-demi: false

minimumReleaseAgeExclude:
  - '@unocss/config@66.7.4'
  - '@unocss/core@66.7.4'
  - '@unocss/eslint-plugin@66.7.4'
  - '@unocss/rule-utils@66.7.4'
  - prettier@3.9.4

catalog:
  '@antfu/eslint-config': ^9.1.0
  '@giscus/vue': ^3.1.1
  '@iconify-json/ant-design': ^1.2.7
  '@iconify-json/material-symbols': ^1.2.81
  '@iconify-json/ri': ^1.2.10
  '@iconify-json/simple-icons': ^1.2.88
  '@vueuse/core': ^14.3.0
  '@unocss/eslint-plugin': ^66.7.4
  eslint: ^10.6.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-format: ^2.0.1
  prettier: ^3.9.4
  sponsorkit: ^17.1.1
  typescript: ^6.0.3
  valaxy: ^0.28.11
  valaxy-addon-components: ^0.1.0
  vue-gtag-next: ^1.14.0
  unocss: ^66.7.3
  vite-plugin-font: ^5.1.2
  vite: ^8.1.0
  vite-plugin-vue-layouts-next: ^2.1.0
  unplugin-vue-router: ^0.19.2
  vue: ^3.5.39
  '@trivago/prettier-plugin-sort-imports': ^6.0.2
  vue-i18n: ^11.4.6
