catalogMode: prefer
cleanupUnusedCatalogs: true

packages:
  - addons/*
  - legacy
  - site
  - demo
  - theme

allowBuilds:
  '@parcel/watcher': true
  cn-font-split: true
  core-js: false
  esbuild: true
  koffi: true
  protobufjs: true
  sharp: false
  vue-demi: false
  workerd: true

minimumReleaseAgeExclude:
  - '@unocss/config@66.7.4'
  - '@unocss/core@66.7.4'
  - '@unocss/eslint-plugin@66.7.4'
  - '@unocss/rule-utils@66.7.4'
  - prettier@3.9.4 || 3.9.6
  - '@cloudflare/workerd-darwin-64@1.20260721.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260721.1'
  - '@cloudflare/workerd-linux-64@1.20260721.1'
  - '@cloudflare/workerd-linux-arm64@1.20260721.1'
  - '@cloudflare/workerd-windows-64@1.20260721.1'
  - miniflare@4.20260721.0
  - workerd@1.20260721.1
  - wrangler@4.113.0

catalog:
  '@antfu/eslint-config': ^9.1.0
  '@giscus/vue': ^3.1.1
  '@iconify-json/ic': ^1.2.4
  '@iconify-json/material-symbols': ^1.2.86
  '@iconify-json/mingcute': ^1.2.7
  '@iconify-json/ri': ^1.2.10
  '@iconify-json/simple-icons': ^1.2.91
  '@iconify-json/tabler': ^1.2.37
  '@poupe/material-color-utilities': 0.4.1
  '@trivago/prettier-plugin-sort-imports': ^6.0.2
  '@unocss/eslint-config': ^66.7.5
  '@unocss/eslint-plugin': ^66.7.5
  '@vueuse/core': ^14.3.0
  '@waline/client': 3.15.2
  artalk: ^2.9.1
  eslint: ^10.7.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-format: ^2.0.1
  medium-zoom: ^1.1.0
  prettier: ^3.9.6
  sponsorkit: ^17.1.1
  typescript: ^6.0.3
  unocss: ^66.7.5
  valaxy: ^0.28.11
  valaxy-addon-algolia: ^0.2.1
  valaxy-addon-artalk: ^0.1.4
  valaxy-addon-components: ^0.1.0
  valaxy-addon-twikoo: ^0.0.4
  valaxy-addon-waline: ^0.2.1
  vite: ^8.1.5
  vite-plugin-font: ^5.1.2
  vite-plugin-vue-layouts-next: ^2.1.0
  vitest: ^4.1.10
  vue: ^3.5.40
  vue-gtag-next: ^1.14.0
  vue-i18n: ^11.4.7
  vue-router: ^5.2.0
  vue-tsc: ^3.3.7
  wrangler: ^4.113.0

patchedDependencies:
  sponsorkit@17.1.1: patches/sponsorkit@17.1.1.patch
