/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes/': RouteRecordInfo<
      '/notes/',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/draft': RouteRecordInfo<
      '/posts/draft',
      '/posts/draft',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/i18n': RouteRecordInfo<
      '/posts/i18n',
      '/posts/i18n',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/markdown': RouteRecordInfo<
      '/posts/markdown',
      '/posts/markdown',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-01': RouteRecordInfo<
      '/posts/pagination-test-01',
      '/posts/pagination-test-01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-02': RouteRecordInfo<
      '/posts/pagination-test-02',
      '/posts/pagination-test-02',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-03': RouteRecordInfo<
      '/posts/pagination-test-03',
      '/posts/pagination-test-03',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-04': RouteRecordInfo<
      '/posts/pagination-test-04',
      '/posts/pagination-test-04',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-05': RouteRecordInfo<
      '/posts/pagination-test-05',
      '/posts/pagination-test-05',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-06': RouteRecordInfo<
      '/posts/pagination-test-06',
      '/posts/pagination-test-06',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-07': RouteRecordInfo<
      '/posts/pagination-test-07',
      '/posts/pagination-test-07',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-08': RouteRecordInfo<
      '/posts/pagination-test-08',
      '/posts/pagination-test-08',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-09': RouteRecordInfo<
      '/posts/pagination-test-09',
      '/posts/pagination-test-09',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pagination-test-10': RouteRecordInfo<
      '/posts/pagination-test-10',
      '/posts/pagination-test-10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/test': RouteRecordInfo<
      '/posts/test',
      '/posts/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    '../theme/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    '../node_modules/.pnpm/valaxy@0.28.11_@babel+parse_83e3c5ba95c0a48db99e224b20bf64be/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/about.md': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/notes/index.md': {
      routes:
        | '/notes/'
      views:
        | never
      pathParamNames:
        | never
    }
    '../theme/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/posts/draft.md': {
      routes:
        | '/posts/draft'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/i18n.md': {
      routes:
        | '/posts/i18n'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/markdown.md': {
      routes:
        | '/posts/markdown'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-01.md': {
      routes:
        | '/posts/pagination-test-01'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-02.md': {
      routes:
        | '/posts/pagination-test-02'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-03.md': {
      routes:
        | '/posts/pagination-test-03'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-04.md': {
      routes:
        | '/posts/pagination-test-04'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-05.md': {
      routes:
        | '/posts/pagination-test-05'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-06.md': {
      routes:
        | '/posts/pagination-test-06'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-07.md': {
      routes:
        | '/posts/pagination-test-07'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-08.md': {
      routes:
        | '/posts/pagination-test-08'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-09.md': {
      routes:
        | '/posts/pagination-test-09'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pagination-test-10.md': {
      routes:
        | '/posts/pagination-test-10'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/test.md': {
      routes:
        | '/posts/test'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
