name: Auto Update Sponsor List

permissions: write-all

on:
  push:
    paths:
      - "blog/sponsorkit.config.js"
      - "blog/public/sponsors/direct-raw.json"
      - ".github/workflows/sponsor.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sponsor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: true
      - uses: pnpm/action-setup@v6
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
      - name: Run Job
        run: |-
          pnpm i
          cd blog
          export SPONSORKIT_AFDIAN_TOKEN=${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}
          export SPONSORKIT_AFDIAN_USER_ID=${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          pnpm sponsor
          if [[ -n "$(git status -s)" ]]; then
            git add .
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git commit -m "chore(sponsor-ci): update sponsor SVGs"
            git push
          else
            echo "No changes detected."
          fi
